<<<<<<< HEAD
import "@/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
=======
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
>>>>>>> 144bbef4a98eb68f006f51e30e8987968a5f03aa

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
=======
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
>>>>>>> 144bbef4a98eb68f006f51e30e8987968a5f03aa
}
